# Generated by Django 4.1 on 2022-09-09 09:28

from django.db import migrations, models
import django.db.models.deletion
import prescriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('prescriptions', '0002_alter_chronicprescription_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicprescription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_prescription', to='customers.customer', validators=[prescriptions.models.prescriptions_for_patient_only]),
        ),
    ]
