# Generated by Django 4.1 on 2022-09-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('prescriptions', '0003_alter_chronicprescription_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicprescription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_prescription', to='customers.customer'),
        ),
    ]
