# Generated by Django 4.1 on 2022-09-09 08:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prescriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicPrescription',
            fields=[
                ('chronic_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, validators=[prescriptions.models.no_future_date, prescriptions.models.no_old_date])),
                ('duration', models.PositiveIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(30)])),
                ('notification_status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_prescription', to='customers.customer', validators=[prescriptions.models.prescriptions_for_patient_only])),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('prescription_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='prescriptions.chronicprescription')),
            ],
            options={
                'managed': True,
                'unique_together': {('drug_name', 'prescription')},
            },
        ),
    ]
