# Generated by Django 4.1 on 2022-08-18 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicPrescription',
            fields=[
                ('chronic_presecription_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(90)])),
                ('notification_status', models.BooleanField(default=True)),
            ],
        ),
    ]
