# Generated by Django 4.1 on 2022-08-18 13:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronicprescription',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='chronicprescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='chronicprescription',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.datetime(2022, 8, 18, 13, 24, 44, 381980, tzinfo=datetime.timezone.utc))), name='check_no_future_prescription'),
        ),
    ]
