# Generated by Django 4.1 on 2022-08-18 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_chronicprescription_check_no_future_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chronicprescription',
            name='check_no_future_prescription',
        ),
        migrations.AlterField(
            model_name='chronicprescription',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='chronicprescription',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2022, 8, 18))), name='check_no_future_prescription'),
        ),
    ]
