# Generated by Django 4.1 on 2022-08-18 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_remove_chronicprescription_check_no_future_prescription_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chronicprescription',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', datetime.date(2022, 5, 20))), name='check_no_old_prescription'),
        ),
    ]
