# Generated by Django 4.1 on 2022-08-18 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_chronicprescription_check_no_old_prescription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chronicprescription',
            name='check_no_future_prescription',
        ),
        migrations.RemoveConstraint(
            model_name='chronicprescription',
            name='check_no_old_prescription',
        ),
        migrations.AddConstraint(
            model_name='chronicprescription',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2022, 8, 18)), ('date__gte', datetime.date(2022, 5, 20))), name='check_prescription_date_range'),
        ),
    ]
