# Generated by Django 4.1 on 2022-08-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_remove_chronicprescription_check_no_future_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('prescription_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250, unique=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='prescriptions.chronicprescription')),
            ],
        ),
    ]
