# Generated by Django 4.1 on 2022-08-18 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
