# Generated by Django 4.1 on 2022-08-19 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_alter_prescriptionitem_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chronicprescription',
            name='check_prescription_date_range',
        ),
        migrations.AddConstraint(
            model_name='chronicprescription',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2022, 8, 19)), ('date__gte', datetime.date(2022, 5, 21))), name='check_prescription_date_range'),
        ),
    ]
