# Generated by Django 4.1 on 2022-08-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_alter_chronicprescription_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronicprescription',
            old_name='chronic_presecription_id',
            new_name='chronic_prescription_id',
        ),
    ]
