# Generated by Django 4.1 on 2022-09-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_phones'),
        ('prescriptions', '0015_chronicprescription_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicprescription',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chronic_prescription', to='customers.customer'),
        ),
    ]
