# Generated by Django 4.1 on 2022-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('copharmacy', 'CoPharmacy')], default='patient', max_length=10),
        ),
    ]
