# Generated by Django 4.1 on 2022-08-25 14:03

import customers.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, validators=[customers.models.validate_phone_number, customers.models.prevent_replicated_phone]), blank=True, default=list, null=True, size=None),
        ),
    ]
