# Generated by Django 4.1 on 2022-09-09 08:45

import customers.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, validators=[customers.models.validate_phone_number, customers.models.prevent_replicated_phone]), blank=True, default=list, null=True, size=None)),
                ('customer_type', models.CharField(choices=[('patient', 'Patient'), ('copharmacy', 'CoPharmacy')], default='patient', max_length=10)),
            ],
        ),
    ]
